Catalogs = [
    {'name': 'Мужское'},
    {'name': 'Женское'},
    {'name': 'Футболки для мужчин',
     'parent': 0},
    {'name': 'Рубашки для мужчин',
     'parent': 0},
    {'name': 'Брюки для мужчин',
     'parent': 0},
    {'name': 'Официальная Одежда для мужчин',
     'parent': 0},
    {'name': 'Часы для мужчин',
     'parent': 0},
    {'name': 'Толстовки для мужчин',
     'parent': 0},
    {'name': 'Джинсы для мужчин',
     'parent': 0},
    {'name': 'Обувь для мужчин',
     'parent': 0},
    {'name': 'Спортивная одежда для мужчин',
     'parent': 0},
    {'name': 'Футболки для женщин',
     'parent': 1},
    {'name': 'Рубашки для женщин',
     'parent': 1},
    {'name': 'Брюки для женщин',
     'parent': 1},
    {'name': 'Официальная Одежда для женщин',
     'parent': 1},
    {'name': 'Часы для женщин',
     'parent': 1},
    {'name': 'Толстовки для женщин',
     'parent': 1},
    {'name': 'Джинсы для женщин',
     'parent': 1},
    {'name': 'Обувь для женщин',
     'parent': 1},
    {'name': 'Спортивная одежда для женщин',
     'parent': 1},

]

Products = [{'catalog': Catalogs[3], 'name': 'Рубашка', 'sex': 'M', 'stock': 1000,
             'description': 'Мужская рубашка Bawer выполнена из высококачественного хлопка. Силуэт Slim Fit - плотно сидит по фигуре. Лучше всего подходят для стандартного или худощавого телосложения. Подчёркивает фигуру. Однотонная рубашка с отложным воротником и длинными рукавами застегивается на пуговицы. Произведена мужская рубашка в Турции.',
             'price': 9999, 'discount': 10, },
            {'catalog': Catalogs[12], 'name': 'Блузка', 'sex': 'w', 'stock': 1000,
             'description': 'Универсальная блузка женская, которая подойдет под любой повод и вид одежды, будь то джинсы, юбка, брюки, лосины или шорты. Блузка с баской может использоваться в качестве праздничной, вечерней, повседневной, офисной и школьной. Приталенная трикотажная кофточка делает силуэт более стройным, изящным и женственным. ',
             'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[2], 'name': 'Футболка', 'sex': 'M', 'stock': 1000,
             'description': 'Футболка мужская хлопковая однотонная базовая', 'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[11], 'name': 'Футболка', 'sex': 'W', 'stock': 1000,
             'description': 'Футболка мужская хлопковая однотонная базовая', 'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[4], 'name': 'Брюки', 'sex': 'M', 'stock': 1000,
             'description': 'Брюки мужские спортивные сшиты из приятной к телу хлопковой ткани, обладающей воздухопроницаемостью. Штаны мужские спортивные на средней посадке, не сковывают движений, удобны в носке.',
             'price': 9999, 'discount': 10, },
            {'catalog': Catalogs[13], 'name': 'Брюки', 'sex': 'W', 'stock': 1000,
             'description': 'Брюки женские классические с высокой посадкой или брюки палаццо станут украшением гардероба любой девушки и женщины.',
             'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[5], 'name': 'Смокинг', 'sex': 'M', 'stock': 1000,
             'description': 'Классический смокинг Slim fit (сильно приталенная консрукция), подходит для людей с телосложением без живота. ',
             'price': 9999, 'discount': 10, },
            {'catalog': Catalogs[16], 'name': 'Смокинг', 'sex': 'W', 'stock': 1000,
             'description': 'Безупречный белый смокинг Batista. Женственный минималистичный жакет, модель Slim, немного маломерит за счет узкой посадки и укороченного рукава.',
             'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[7], 'name': 'Толстовка', 'sex': 'M', 'stock': 1000,
             'description': 'Setner - Do You Still Think Of Me худи без начеса. Немного скучной информаци о толстовке: худи из хлопка, футер 3-ех нитка. Тостовка с широким кроем ( оверсайз ), слегка опущенная плечевая линия. ',
             'price': 9999, 'discount': 10, },
            {'catalog': Catalogs[16], 'name': 'Толстовка', 'sex': 'W', 'stock': 1000,
             'description': 'Женское оверсайз худи "Maybe" - длинное и тёплое, с двойным капюшоном, изготовлено из качественного трикотажа с начёсом.',
             'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[8], 'name': 'Джинсы', 'sex': 'M', 'stock': 1000,
             'description': 'Качественные стильные джинсы прямого кроя classic fit насыщенного синего цвета. На поясе шлевки для ремня, сзади фирменная нашивка бренда контрастного рыжего цвета.',
             'price': 9999, 'discount': 10, },
            {'catalog': Catalogs[17], 'name': 'Джинсы', 'sex': 'W', 'stock': 1000,
             'description': 'Модные узкие обтягивающие женские джинсы американка из премиального хлопка от бренда LEMIBREND. Классические облегающие скини - тренд моделей джинс 2022 года. ',
             'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[9], 'name': 'Кросовки', 'sex': 'M', 'stock': 1000,
             'description': 'текстиль, синтетический материал', 'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[18], 'name': 'Кросовки', 'sex': 'W', 'stock': 1000,
             'description': 'текстиль, синтетический материал', 'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[10], 'name': 'Спортивный костюм', 'sex': 'M', 'stock': 1000,
             'description': 'хлопок 80%, полиэстер 20%', 'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[19], 'name': 'Спортивный костюм', 'sex': 'W', 'stock': 1000,
             'description': 'хлопок 80%, полиэстер 20%', 'price': 9999, 'discount': 10, },

            {'catalog': Catalogs[6], 'name': 'Часы', 'sex': 'M', 'stock': 1000,
             'description': 'Изысканный дизайн Смарт-часывыполненыиз премиум материалов. Отличаются превосходным дизайном.Сапфировое стекло, титановый корпус икерамическая задняя панель обеспечивают отличную устойчивость к износу и комфортное ношение.',
             'price': 9999, 'discount': 10, },
            {'catalog': Catalogs[6], 'name': 'Часы', 'sex': 'W', 'stock': 1000,
             'description': 'Стильные и красивые женские часы для твоего повседневного образа. Сдержанный, и в тоже время стильный дизайн часов позволяет носить их к любому виду одежды.',
             'price': 9999, 'discount': 10, },
            ]

ProductImages = [
    {'product': Products[0], 'image': 'товары/Рубашка М/8612522-1.jpg', },
    {'product': Products[0], 'image': 'товары/Рубашка М/8612522-3.jpg', },
    {'product': Products[0], 'image': 'товары/Рубашка М/8612522-6.jpg', },
    {'product': Products[0], 'image': 'товары/Рубашка М/8612522-8.jpg', },
    {'product': Products[0], 'image': 'товары/Рубашка М/8612522-10.jpg', },
    {'product': Products[0], 'image': 'товары/Рубашка М/8612522-11.jpg'},
    {'product': Products[1], 'image': 'товары/Рубашка Ж/9528261-1.jpg', },
    {'product': Products[1], 'image': 'товары/Рубашка Ж/9528261-2.jpg', },
    {'product': Products[1], 'image': 'товары/Рубашка Ж/9528261-4.jpg', },
    {'product': Products[1], 'image': 'товары/Рубашка Ж/9528261-5.jpg', },
    {'product': Products[1], 'image': 'товары/Рубашка Ж/9528261-6.jpg'},
    {'product': Products[2], 'image': 'товары/Футболка М/12801485-3.jpg', },
    {'product': Products[2], 'image': 'товары/Футболка М/12801485-3.jpg', },
    {'product': Products[2], 'image': 'товары/Футболка М/12801485-3.jpg', },
    {'product': Products[2], 'image': 'товары/Футболка М/78457050-1.jpg', },
    {'product': Products[2], 'image': 'товары/Футболка М/78457050-1.jpg', },
    {'product': Products[2], 'image': 'товары/Футболка М/78457050-1.jpg', },
    {'product': Products[2], 'image': 'товары/Футболка М/78457050-1.jpg', },
    {'product': Products[2], 'image': 'товары/Футболка М/footbolka_1_M.jpg'},
    {'product': Products[3], 'image': 'товары/Футболка Ж/12801485-4.jpg', },
    {'product': Products[3], 'image': 'товары/Футболка Ж/12801485-5.jpg', },
    {'product': Products[3], 'image': 'товары/Футболка Ж/12801485-6.jpg', },
    {'product': Products[3], 'image': 'товары/Футболка Ж/12801485-7.jpg', },
    {'product': Products[3], 'image': 'товары/Футболка Ж/12801488-1.jpg', },
    {'product': Products[3], 'image': 'товары/Футболка Ж/12801488-2.jpg', },
    {'product': Products[3], 'image': 'товары/Футболка Ж/12801488-3.jpg', },
    {'product': Products[3], 'image': 'товары/Футболка Ж/12801488-4.jpg'},
    {'product': Products[4], 'image': 'товары/брюки М/68988778-1.jpg', },
    {'product': Products[4], 'image': 'товары/брюки М/68988778-3.jpg', },
    {'product': Products[4], 'image': 'товары/брюки М/68988778-4.jpg', },
    {'product': Products[4], 'image': 'товары/брюки М/68988778-5.jpg', },
    {'product': Products[4], 'image': 'товары/брюки М/68988778-8.jpg'},
    {'product': Products[5], 'image': 'товары/Брюки Ж/77421106-1.jpg', },
    {'product': Products[5], 'image': 'товары/Брюки Ж/77421106-2.jpg', },
    {'product': Products[5], 'image': 'товары/Брюки Ж/77421106-3.jpg', },
    {'product': Products[5], 'image': 'товары/Брюки Ж/77421106-4.jpg', },
    {'product': Products[5], 'image': 'товары/Брюки Ж/77421106-6.jpg', },
    {'product': Products[5], 'image': 'товары/Брюки Ж/77421106-7.jpg', },
    {'product': Products[5], 'image': 'товары/Брюки Ж/77421106-8.jpg', },
    {'product': Products[5], 'image': 'товары/Брюки Ж/77421106-9.jpg'},
    {'product': Products[6], 'image': 'товары/Смокинг М/16353631-1.jpg', },
    {'product': Products[6], 'image': 'товары/Смокинг М/16353631-3.jpg', },
    {'product': Products[6], 'image': 'товары/Смокинг М/16353631-4.jpg', },
    {'product': Products[6], 'image': 'товары/Смокинг М/16353631-5.jpg', },
    {'product': Products[6], 'image': 'товары/Смокинг М/16353631-2.jpg'},
    {'product': Products[7], 'image': 'товары/Смокинг Ж/10078540-1.jpg', },
    {'product': Products[7], 'image': 'товары/Смокинг Ж/10078540-2.jpg', },
    {'product': Products[7], 'image': 'товары/Смокинг Ж/10078540-3.jpg', },
    {'product': Products[7], 'image': 'товары/Смокинг Ж/10078540-4.jpg', },
    {'product': Products[7], 'image': 'товары/Смокинг Ж/10078540-5.jpg', },
    {'product': Products[7], 'image': 'товары/Смокинг Ж/10078540-6.jpg'},
    {'product': Products[8], 'image': 'товары/Толстовка М/33479173-1.jpg', },
    {'product': Products[8], 'image': 'товары/Толстовка М/33479173-2.jpg', },
    {'product': Products[8], 'image': 'товары/Толстовка М/33479173-6.jpg', },
    {'product': Products[8], 'image': 'товары/Толстовка М/33479173-10.jpg', },
    {'product': Products[8], 'image': 'товары/Толстовка М/33479173-12.jpg'},
    {'product': Products[9], 'image': 'товары/Толстовка Ж/14950980-1.jpg', },
    {'product': Products[9], 'image': 'товары/Толстовка Ж/14950980-2.jpg', },
    {'product': Products[9], 'image': 'товары/Толстовка Ж/14950980-3.jpg', },
    {'product': Products[9], 'image': 'товары/Толстовка Ж/14950980-4.jpg', },
    {'product': Products[9], 'image': 'товары/Толстовка Ж/14950980-5.jpg', },
    {'product': Products[9], 'image': 'товары/Толстовка Ж/14950980-6.jpg'},
    {'product': Products[10], 'image': 'товары/Джинсы М/48655258-1.jpg', },
    {'product': Products[10], 'image': 'товары/Джинсы М/48655258-2.jpg', },
    {'product': Products[10], 'image': 'товары/Джинсы М/48655258-3.jpg', },
    {'product': Products[10], 'image': 'товары/Джинсы М/48655258-5.jpg', },
    {'product': Products[10], 'image': 'товары/Джинсы М/48655258-8.jpg'},
    {'product': Products[11], 'image': 'товары/Джинсы Ж/21401242-1.jpg', },
    {'product': Products[11], 'image': 'товары/Джинсы Ж/21401242-2.jpg', },
    {'product': Products[11], 'image': 'товары/Джинсы Ж/21401242-3.jpg', },
    {'product': Products[11], 'image': 'товары/Джинсы Ж/21401242-4.jpg', },
    {'product': Products[11], 'image': 'товары/Джинсы Ж/21401242-5.jpg', },
    {'product': Products[12], 'image': 'товары/Кросовки М/45926470-1.jpg', },
    {'product': Products[12], 'image': 'товары/Кросовки М/45926470-2.jpg', },
    {'product': Products[12], 'image': 'товары/Кросовки М/45926470-3.jpg', },
    {'product': Products[12], 'image': 'товары/Кросовки М/45926470-4.jpg', },
    {'product': Products[12], 'image': 'товары/Кросовки М/45926470-5.jpg', },
    {'product': Products[12], 'image': 'товары/Кросовки М/45926470-6.jpg', },
    {'product': Products[12], 'image': 'товары/Кросовки М/45926470-7.jpg', },
    {'product': Products[13], 'image': 'товары/Кросовки Ж/18527664-1.jpg', },
    {'product': Products[13], 'image': 'товары/Кросовки Ж/18527664-2.jpg', },
    {'product': Products[13], 'image': 'товары/Кросовки Ж/18527664-3.jpg', },
    {'product': Products[13], 'image': 'товары/Кросовки Ж/18527664-4.jpg', },
    {'product': Products[13], 'image': 'товары/Кросовки Ж/18527664-5.jpg', },
    {'product': Products[13], 'image': 'товары/Кросовки Ж/18527664-6.jpg', },
    {'product': Products[13], 'image': 'товары/Кросовки Ж/18527664-7.jpg', },
    {'product': Products[13], 'image': 'товары/Кросовки Ж/18527664-8.jpg'},
    {'product': Products[14], 'image': 'товары/Спортивки М/18029951-1.jpg', },
    {'product': Products[14], 'image': 'товары/Спортивки М/18029951-2.jpg', },
    {'product': Products[14], 'image': 'товары/Спортивки М/18029951-3.jpg', },
    {'product': Products[14], 'image': 'товары/Спортивки М/18029951-4.jpg', },
    {'product': Products[14], 'image': 'товары/Спортивки М/18029951-5.jpg', },
    {'product': Products[14], 'image': 'товары/Спортивки М/18029951-6.jpg', },
    {'product': Products[15], 'image': 'товары/Спортивки Ж/80654079-1.jpg', },
    {'product': Products[15], 'image': 'товары/Спортивки Ж/80654079-2.jpg', },
    {'product': Products[15], 'image': 'товары/Спортивки Ж/80654079-3.jpg', },
    {'product': Products[15], 'image': 'товары/Спортивки Ж/80654079-4.jpg', },
    {'product': Products[15], 'image': 'товары/Спортивки Ж/80654079-5.jpg', },
    {'product': Products[15], 'image': 'товары/Спортивки Ж/80654079-6.jpg', },
    {'product': Products[15], 'image': 'товары/Спортивки Ж/80654079-7.jpg', },
    {'product': Products[16], 'image': 'товары/Часы М/16233593-1.jpg', },
    {'product': Products[16], 'image': 'товары/Часы М/16233593-2.jpg', },
    {'product': Products[16], 'image': 'товары/Часы М/16233593-3.jpg', },
    {'product': Products[16], 'image': 'товары/Часы М/16233593-4.jpg', },
    {'product': Products[16], 'image': 'товары/Часы М/16233593-5.jpg', },
    {'product': Products[16], 'image': 'товары/Часы М/16233593-8.jpg', },
    {'product': Products[17], 'image': 'товары/Часы Ж/29082758-1.jpg', },
    {'product': Products[17], 'image': 'товары/Часы Ж/29082758-2.jpg', },
    {'product': Products[17], 'image': 'товары/Часы Ж/29082758-3.jpg', },
    {'product': Products[17], 'image': 'товары/Часы Ж/29082758-4.jpg', }]
